DROP TABLE IF EXISTS "useremailotps" CASCADE;
CREATE TABLE IF NOT EXISTS "useremailotps" ("id" SERIAL, "login_otp" VARCHAR(255) NOT NULL, "email" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "userId" BIGINT, PRIMARY KEY("id"), FOREIGN KEY("userId") REFERENCES users("id"));
